<div class="row">
    <a href="<?= $this->url('Acef/Clientes/Grid'); ?>">
        <div class="col-lg-3 col-sm-6 col-xs-12">
            <div class="main-box infographic-box">
                <i class="fa fa-user red-bg"></i>
                <span class="headline">Gestionar</span>
                <span class="value">
                    Clientes
                </span>
            </div>
        </div>
    </a>
    <a href="<?= $this->url('Acef/TablasMaestras/Main'); ?>">
        <div class="col-lg-4 col-sm-6 col-xs-12">
            <div class="main-box infographic-box">
                <i class="fa fa-cog emerald-bg"></i>
                <span class="headline">Administrar</span>
                <span class="value">
                    Tablas Maestras
                </span>
            </div>
        </div>
    </a>
    <!--    <div class="col-lg-3 col-sm-6 col-xs-12">
            <div class="main-box infographic-box">
                <i class="fa fa-money green-bg"></i>
                <span class="headline">Income</span>
                <span class="value">
                    $<span class="timer" data-from="83" data-to="8400" data-speed="900" data-refresh-interval="60">8400</span>
                </span>
            </div>
        </div>
        <div class="col-lg-3 col-sm-6 col-xs-12">
            <div class="main-box infographic-box">
                <i class="fa fa-eye yellow-bg"></i>
                <span class="headline">Monthly Visits</span>
                <span class="value">
                    <span class="timer" data-from="539" data-to="12526" data-speed="1100">12526</span>
                </span>
            </div>
        </div>-->
</div>