<div class="row ">
    <div class="col-lg-12">
        <div class="main-box  clearfix">

            <div class="main-box-header clearfix addPaddingTopCustom" >
                <h2 style="padding: 7px; font-weight: normal; border-bottom: 1px solid #e5e5e5;">Actualización</h2>
            </div>


            <div class="main-box-body clearfi">

                <?php
                $groups = [
                    [
                        'type' => \ZfMetal\Commons\Options\FormGroupConfig::TYPE_VERTICAL,
                        'id' => 'Porcentajes',
                        'title' => 'Porcentajes',
                        'columns' => \ZfMetal\Commons\Consts::COLUMNS_FOUR,
                        'style' => \ZfMetal\Commons\Consts::STYLE_VERTICAL,
                        'fields' => ['porcentajeQuitaIntereses', 'porcentajeQuitaCapital', 'tasa']
                    ],
                    [
                        'type' => \ZfMetal\Commons\Options\FormGroupConfig::TYPE_VERTICAL,
                        'id' => 'Tiempo',
                        'title' => 'Mora',
                        'columns' => \ZfMetal\Commons\Consts::COLUMNS_FOUR,
                        'style' => \ZfMetal\Commons\Consts::STYLE_VERTICAL,
                        'fields' => ['fechaMoraDesde', 'fechaCalculoHasta', 'diasDeMora',]
                    ],
                    [
                        'type' => \ZfMetal\Commons\Options\FormGroupConfig::TYPE_VERTICAL,
                        'id' => 'Preliminares',
                        'title' => 'Preliminares',
                        'columns' => \ZfMetal\Commons\Consts::COLUMNS_FOUR,
                        'style' => \ZfMetal\Commons\Consts::STYLE_VERTICAL,
                        'fields' => ['capital', 'compensa', 'totalIntereses']
                    ],
                    [
                        'type' => \ZfMetal\Commons\Options\FormGroupConfig::TYPE_VERTICAL,
                        'id' => 'Finales',
                        'title' => 'Totales',
                        'columns' => \ZfMetal\Commons\Consts::COLUMNS_FOUR,
                        'style' => \ZfMetal\Commons\Consts::STYLE_VERTICAL,
                        'fields' => ['totalDeudaActualizada', 'quitaInteresesTotalDeudaActualizada', 'quitaDeCapital', 'totalDeudaConQuita']
                    ],
                ];
                ?>

                <?php
                echo $this->renderForm($this->formActualizacion, \ZfMetal\Commons\Consts::STYLE_VERTICAL, \ZfMetal\Commons\Consts::COLUMNS_FOUR, $groups);
                ?>
            </div>
            <div class="main-box-header clearfix addPaddingTopCustom" style="margin-bottom: 8px" ></div>
        </div>
    </div> 
</div>


<script>
    $("#simulacion_actualizacion").submit(function (e) {
        var url = '/acef/deuda-actualizacion/form/' + '<?php echo $this->clienteId ?>';
        $.ajax({
            type: "POST",
            url: url,
            data: $("#simulacion_actualizacion").serialize(),
            success: function (data)
            {
                $("#formActualizacion").html(data);
                ZfMetal_Grid_List_zfmdg_DuedaRefinanciacion();
            }
        });

        e.preventDefault();
    });
    
    
      function cleanActualizacion() {
        $(':input', '#simulacion_actualizacion')
                .not(':button, :submit, :reset, :hidden')
                .val('')
                .removeAttr('checked')
                .removeAttr('selected');

    }
</script>