

<div class="row">
    <div class="col-lg-12">
        <div class="main-box  clearfix">
            <div class="main-box-header clearfix">
                <h2>Usuarios</h2>
            </div>

            <div class="main-box-body clearfix">

                <div class="filter-block pull-right" style="margin-top: 25px; margin-right: 10px">
                    <a href="/admin/users/create" class="btn pull-right btnCustom" >
                        <i class="fa fa-plus-circle fa-lg"></i> 
                        Agregar Usuario
                    </a>
                </div>
                <div class="clearfix"></div>
                <div class="table-responsive">
                    <table class="table user-list table-hover">
                        <thead>

                        <th>ID</th>
                        <th><?= $this->translate('Nombre') ?></th>
                        <th><?= $this->translate('Usuario') ?></th>
                        <th><?= $this->translate('Creado') ?></th>
                        <th>Email</th>
                        <th><?= $this->translate('Activo') ?></th>
                        <th>&nbsp;</th>
                        </thead>
                        <tbody>
                            <?php foreach ($this->dataGrid->getCurrentItems() as $item): ?> 
                                <tr>

                                    <td><?php echo $item->getId(); ?></td>
                                    <td>
                                        <?php if ($this->applicationOptions()->getShowImages()) : ?> 
                                            <img class="img-circle" src="<?= $this->basePath($this->getSecurityOptions()->getProfilePicturePathRelative()) . $item->getImg(); ?>" alt="">
                                        <?php endif; ?>
                                        <span href="#" class="<?php echo $this->applicationOptions()->getShowImages() ? 'user-link' : 'h5' ?>"><?php echo $item->getName(); ?></span><br>
                                        <?php foreach ($item->getRoles() as $rol) : ?>
                                            <span class="label label-info" style="padding: 1px;"><?= $rol->getName(); ?></span>
                                        <?php endforeach; ?>
                                    </td>
                                    <td><?php echo $item->getUsername(); ?></td>
                                    <td>
                                        <?php echo $item->getCreateAt()->format('d/m/Y'); ?>
                                    </td>
                                    <td><?php echo $item->getEmail(); ?></td> 
                                    <td><?php echo ($item->getActive()) ? "<i class='label label-success'>" . $this->translate('Activo') . "</i>" : "<i class='label label-default'>" . $this->translate('Inactivo') . "</i>"; ?></td> 
                                    <td style="width: 20%;">
                                        <a href="/admin/users/view/<?php echo $item->getId(); ?>" class="table-link">
                                            <span class="fa-stack">
                                                <i class="fa fa-square fa-stack-2x"></i>
                                                <i class="fa fa-search-plus fa-stack-1x fa-inverse"></i>
                                            </span>
                                        </a>
                                        <a href="/admin/users/edit/<?php echo $item->getId(); ?>" class="table-link">
                                            <span class="fa-stack">
                                                <i class="fa fa-square fa-stack-2x"></i>
                                                <i class="fa fa-pencil fa-stack-1x fa-inverse"></i>
                                            </span>
                                        </a>
                                        <a href="/admin/users/del/<?php echo $item->getId(); ?>" class="table-link danger">
                                            <span class="fa-stack">
                                                <i class="fa fa-square fa-stack-2x"></i>
                                                <i class="fa fa-trash-o fa-stack-1x fa-inverse"></i>
                                            </span>
                                        </a>
                                        <a href="/admin/users/reset-password/<?php echo $item->getId(); ?>" class="table-link danger">
                                            <span class="fa-stack">
                                                <i class="fa fa-square fa-stack-2x"></i>
                                                <i class="fa fa-lock fa-stack-1x fa-inverse"></i>
                                            </span>
                                        </a>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
                <?php
                echo $this->paginationControl($this->dataGrid->getPaginator(), 'Sliding', 'zf-metal/security/data-grid/paginator', array("queryParams" => $this->dataGrid->getParamsArray(), 'route' => 'zf-metal.admin/users'));
                ?>
            </div>

        </div>

    </div>

</div>


