
<div class="row ">
    <div class="main-box  clearfix">

        <div class="main-box-header clearfix">
            <h2> Nuevo Usuario</h2>
        </div>


        <div class="main-box-body clearfix">

            <?php
            $horizontalGroups = [
                'User' => ['name', 'username', 'email', 'password'],
                'Enable/Disable User' => ['active'],
                'Roles' => ['roles'],
            ];

            $this->form->remove('groups');
            
            $this->form->get('submit')->setAttribute('value', 'Enviar')
                    ->setAttribute('class', 'pull-right btn btnCustom')
                    ->setAttribute('style', 'margin-left: 2px');

            $this->form->add(array(
                'name' => 'cancel',
                'type' => 'Zend\Form\Element\Button',
                'attributes' => array(
                    'value' => "Cancelar",
                    'class' => 'pull-right btn btnCancelCustom',
                    'onclick' => 'window.location.href="' . $this->url('zf-metal.admin/users', array(), array('query' => $this->routeParams), true) . '"',
                ),
                'options' => array(
                    'label' => 'Cancelar',
                )
            ));
            
            echo $this->renderForm($this->form, \ZfMetal\Commons\Consts::STYLE_VERTICAL, \ZfMetal\Commons\Consts::COLUMNS_TWO, $horizontalGroups);
            ?>
        </div>

    </div>

</div>
