
<div class="row ">
    <div class="main-box  clearfix">

        <div class="main-box-header clearfix">
            <h2> Edición de Usuario</h2>
        </div>


        <div class="main-box-body clearfix">
            <?php
            $groups = [
            [
                'type' => \ZfMetal\Commons\Options\FormGroupConfig::TYPE_HORIZONTAL,
                'id' => 'User',
                'title' => "User",
                'columns' => \ZfMetal\Commons\Consts::COLUMNS_TWO,
                'style' => \ZfMetal\Commons\Consts::STYLE_VERTICAL,
                'fields' => ['name', 'username', 'email', 'password']
            ],
            [
                'type' => \ZfMetal\Commons\Options\FormGroupConfig::TYPE_VERTICAL,
                'id' => 'enableUser',
                'title' => null,
                'columns' => \ZfMetal\Commons\Consts::COLUMNS_ONE,
                'style' => \ZfMetal\Commons\Consts::STYLE_VERTICAL,
                'fields' => ['active']
            ],
            [
                'type' => \ZfMetal\Commons\Options\FormGroupConfig::TYPE_VERTICAL,
                'id' => 'Roles',
                'title' => 'Roles',
                'columns' => \ZfMetal\Commons\Consts::COLUMNS_ONE,
                'style' => \ZfMetal\Commons\Consts::STYLE_VERTICAL,
                'fields' => ['roles']
            ],
        ];
            
             $this->form->remove('groups');
            
            $this->form->get('submit')->setAttribute('value', 'Enviar')
                    ->setAttribute('class', 'pull-right btn btnCustom')
                    ->setAttribute('style', 'margin-left: 2px');

            $this->form->add(array(
                'name' => 'cancel',
                'type' => 'Zend\Form\Element\Button',
                'attributes' => array(
                    'value' => "Cancelar",
                    'class' => 'pull-right btn btnCancelCustom',
                    'onclick' => 'window.location.href="' . $this->url('zf-metal.admin/users', array(), array('query' => $this->routeParams), true) . '"',
                ),
                'options' => array(
                    'label' => 'Cancelar',
                )
            ));

            echo $this->renderForm($this->form, \ZfMetal\Commons\Consts::STYLE_VERTICAL, \ZfMetal\Commons\Consts::COLUMNS_TWO, $groups);
            ?>
        </div>

    </div>
</div>

<style>
    .multi-check label{
        padding: 10px ! important;
        margin: 5px ! important;
    }

</style>
