<div class="row">

    <div class="main-box clearfix">

        <?php if ($this->grid->getOptions()->getTitle()): ?>

            <div class="main-box-header clearfix">
                <h2> <?php echo $this->grid->getOptions()->getTitle(); ?></h2>
            </div>

        <?php endif; ?>

        <div class="main-box-body clearfix">
            <div id="<?php echo $this->grid->getId(); ?>" >

                <div class="filter-block pull-right" style="margin-top: 25px; margin-right: 10px">
                    <div class="form-group pull-left">
                        <input class="form-control" placeholder="Search..." type="text">
                        <i class="fa fa-search search-icon"></i>
                    </div>

                    <?php if ($this->grid->getOptions()->getCrudConfig()->getAdd()->getEnable()): ?>
                        <a <?php echo $this->grid->getCrudColumn()->getAdd()["action"]; ?>
                            class="btn pull-right btnCustom" >
                            <i class="fa fa-plus-circle fa-lg"></i> <?php echo $this->grid->getCrudColumn()->getAdd()["value"]; ?>
                        </a>
                    <?php endif; ?>
                </div>
                <div class="clearfix"></div>

                <div class="main-box-body clearfix">
                    <div class="table-responsive">
                        <table class="table table-hover dataTable no-footer <?php echo $this->grid->getTableClass(); ?>">
                            <thead>
                                <tr>
                                    <?php foreach ($this->grid->getColumns() as $column): ?>
                                        <?php if (!$column->getHidden()): ?>

                                            <?php if ($column->getType() != "extra" && $column->getType() != "crud"): ?>
                                                <th>                                    
                                                    <?php echo $this->translate((string) $column); ?>
                                                    <!--SORT-->
                                                    <?php if ($this->grid->getSort() && $this->grid->getSort()->getBy() == $column->getName()): ?>
                                                        <?php if ($this->grid->getSort()->getDirection() == "DESC"): ?>
                                                            <a class="sorting_desc" onclick="cdiOrder_<?php echo $this->grid->getId(); ?>('<?php echo $this->url($this->route, array(), array('query' => array('sortBy' => $column->getName(), "sortDirection" => "ASC") + $this->routeParams), true); ?>')"></a>
                                                        <?php elseif ($this->grid->getSort()->getDirection() == "ASC"): ?>
                                                            <a class="sorting_asc" onclick="cdiOrder_<?php echo $this->grid->getId(); ?>('<?php echo $this->url($this->route, array(), array('query' => array('sortBy' => $column->getName(), "sortDirection" => "DESC") + $this->routeParams), true); ?>')"></a>
                                                        <?php endif; ?>
                                                    <?php else: ?>
                                                        <a class="sorting" onclick="cdiOrder_<?php echo $this->grid->getId(); ?>('<?php echo $this->url($this->route, array(), array('query' => array('sortBy' => $column->getName(), "sortDirection" => "DESC") + $this->routeParams), true); ?>')"></a>
                                                    <?php endif; ?>
                                                </th>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    <?php endforeach; ?>
                                    <th>&nbsp;</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php if (count($this->grid->getRow())): ?>
                                    <?php foreach ($this->grid->getRow() as $data): ?>
                                        <tr>
                                            <?php foreach ($this->grid->getColumns() as $column): ?>
                                                <?php if (!$column->getHidden()): ?>
                                                    <td class="<?php echo $column->getTdClass(); ?>">
                                                        <?php //TODO - echo $column->getHtmlBegin(); ?>

                                                        <?php echo $this->GridField($column, $data); ?>

                                                        <?php //TODO - echo $column->getHtmlEnd(); ?>

                                                    </td>
                                                <?php endif; ?>
                                            <?php endforeach; ?>
                                        </tr>
                                    <?php endforeach; ?>
                                <?php endif; ?>
                            </tbody>
                        </table>
                    </div>

                </div>


                <?php
                echo $this->paginationControl($this->grid->getPaginator(), 'Sliding', $this->partialPagination, array("routeParams" => $this->routeParams,
                    'route' => $this->route));
                ?>


                <?php echo $this->GridCrud($this->grid->getId()); ?>

            </div>

        </div>
    </div>
</div>