<div class="row ">
    <div class="col-lg-12">
        <div class="main-box  clearfix">

            <div class="main-box-header clearfix" >
                <h2 style="padding: 7px; font-weight: normal; border-bottom: 1px solid #e5e5e5;">Actualización</h2>
            </div>


            <div class="main-box-body clearfix">

                <?php
                $groups = [
                    [
                        'type' => \ZfMetal\Commons\Options\FormGroupConfig::TYPE_VERTICAL,
                        'id' => 'Porcentajes',
                        'title' => 'Porcentajes',
                        'columns' => \ZfMetal\Commons\Consts::COLUMNS_FOUR,
                        'style' => \ZfMetal\Commons\Consts::STYLE_VERTICAL,
                        'fields' => ['porcentaje_quita_intereses','porcentaje_quita_capital','tasa']
                    ],
                    [
                        'type' => \ZfMetal\Commons\Options\FormGroupConfig::TYPE_VERTICAL,
                        'id' => 'Tiempo',
                        'title' => 'Mora',
                        'columns' => \ZfMetal\Commons\Consts::COLUMNS_FOUR,
                        'style' => \ZfMetal\Commons\Consts::STYLE_VERTICAL,
                        'fields' => [ 'fecha_mora_desde', 'fecha_calculo_hasta', 'dias_de_mora',]
                    ],
                    [
                        'type' => \ZfMetal\Commons\Options\FormGroupConfig::TYPE_VERTICAL,
                        'id' => 'Preliminares',
                        'title' => 'Preliminares',
                        'columns' => \ZfMetal\Commons\Consts::COLUMNS_FOUR,
                        'style' => \ZfMetal\Commons\Consts::STYLE_VERTICAL,
                        'fields' => ['capital', 'compensa', 'total_intereses']
                    ],
                    [
                        'type' => \ZfMetal\Commons\Options\FormGroupConfig::TYPE_VERTICAL,
                        'id' => 'Finales',
                        'title' => 'Totales',
                        'columns' => \ZfMetal\Commons\Consts::COLUMNS_FOUR,
                        'style' => \ZfMetal\Commons\Consts::STYLE_VERTICAL,
                        'fields' => ['total_deuda_actualizada', 'quita_intereses_total_deuda_actualizada', 'quita_de_capital', 'total_deuda_con_quita']
                    ],
                ];
                ?>

                <?php
                echo $this->renderForm($this->formActualizacion, \ZfMetal\Commons\Consts::STYLE_VERTICAL, \ZfMetal\Commons\Consts::COLUMNS_FOUR, $groups);
                ?>
            </div>

        </div>
    </div> 
</div>