<div class="row ">
  
    <div class="col-lg-12">
        <div class="main-box  clearfix">

            <div class="main-box-header clearfix addPaddingTopCustom">
                <h2 style="padding: 7px; font-weight: normal; border-bottom: 1px solid #e5e5e5;">Refinanciación</h2>
            </div>


            <div class="main-box-body clearfix">
                
                 <?php
                $groups = [
                    [
                        'type' => \ZfMetal\Commons\Options\FormGroupConfig::TYPE_VERTICAL,
                        'id' => 'Parametros',
                        'title' => 'Parametros',
                        'columns' => \ZfMetal\Commons\Consts::COLUMNS_THREE,
                        'style' => \ZfMetal\Commons\Consts::STYLE_VERTICAL,
                        'fields' => ['total_deuda_con_quita','anticipo','meses_cuentas']
                    ],
                     [
                        'type' => \ZfMetal\Commons\Options\FormGroupConfig::TYPE_VERTICAL,
                        'id' => 'Parametros 2',
                        'title' => '<br>',
                        'columns' => \ZfMetal\Commons\Consts::COLUMNS_THREE,
                        'style' => \ZfMetal\Commons\Consts::STYLE_VERTICAL,
                        'fields' => ['interes','cantidad_cuotas','cuota_por_anio']
                    ],
                    [
                        'type' => \ZfMetal\Commons\Options\FormGroupConfig::TYPE_VERTICAL,
                        'id' => 'Final',
                        'title' => 'Totales',
                        'columns' => \ZfMetal\Commons\Consts::COLUMNS_THREE,
                        'style' => \ZfMetal\Commons\Consts::STYLE_VERTICAL,
                        'fields' => [ 'tasa', 'monto_refinanciar', 'monto_de_cuota',]
                    ],
                   
                ];
                ?>
                
                <?php
                echo $this->renderForm($this->formRefinanciacion, \ZfMetal\Commons\Consts::STYLE_VERTICAL, \ZfMetal\Commons\Consts::COLUMNS_FOUR, $groups);
                ?>
            </div>
        </div>
    </div>
</div>