<div class="row ">
    <div class="col-lg-12">
        <div class="main-box  clearfix">

            <div class="main-box-header clearfix">
                <h2>Refinanciación</h2>
            </div>


            <div class="main-box-body clearfix">
                <?php
                echo $this->renderForm($this->formRefinanciacion, \ZfMetal\Commons\Consts::STYLE_VERTICAL, \ZfMetal\Commons\Consts::COLUMNS_FOUR, []);
                ?>
            </div>
        </div>
    </div>
</div>