
<div class="row ">
    <div class="col-lg-12">
        <div class="main-box  clearfix">

            <div class="main-box-header clearfix">
                <h2>Actualización</h2>
            </div>


            <div class="main-box-body clearfix">
                
                <?php 
                $groups =  [
                    [
                        'type' => \ZfMetal\Commons\Options\FormGroupConfig::TYPE_VERTICAL,
                        'id' => 'first',
                        'title' => 'first',
                        'columns' => \ZfMetal\Commons\Consts::COLUMNS_FOUR,
                        'style' => \ZfMetal\Commons\Consts::STYLE_VERTICAL,
                        'fields' => ['porcentaje_quita_intereses',]
                    ],
                    [
                        'type' => \ZfMetal\Commons\Options\FormGroupConfig::TYPE_VERTICAL,
                        'id' => 'second',
                        'title' => 'second',
                        'columns' => \ZfMetal\Commons\Consts::COLUMNS_FOUR,
                        'style' => \ZfMetal\Commons\Consts::STYLE_VERTICAL,
                        'fields' => ['tasa', 'fecha_mora_desde', 'fecha_calculo_hasta', 'dias_de_mora',]
                    ],
                    [
                        'type' => \ZfMetal\Commons\Options\FormGroupConfig::TYPE_VERTICAL,
                        'id' => 'third',
                        'title' => 'third',
                        'columns' => \ZfMetal\Commons\Consts::COLUMNS_FOUR,
                        'style' => \ZfMetal\Commons\Consts::STYLE_VERTICAL,
                        'fields' => [ 'capital', 'compensa', 'total_intereses']
                    ],
                    
                    [
                        'type' => \ZfMetal\Commons\Options\FormGroupConfig::TYPE_VERTICAL,
                        'id' => 'fourth',
                        'title' => 'fourth',
                        'columns' => \ZfMetal\Commons\Consts::COLUMNS_FOUR,
                        'style' => \ZfMetal\Commons\Consts::STYLE_VERTICAL,
                        'fields' => [ 'total_deuda_actualizada', 'quita_intereses_total_deuda_actualizada', 'quita_de_capital','total_deuda_con_quita']
                    ],
                ];
                
                ?>
                
                <?php
                echo $this->renderForm($this->formActualizacion, \ZfMetal\Commons\Consts::STYLE_VERTICAL, \ZfMetal\Commons\Consts::COLUMNS_FOUR,$groups);
                ?>
            </div>

        </div>
    </div>

    <div class="col-lg-12">
        <div class="main-box  clearfix">

            <div class="main-box-header clearfix">
                <h2>Refinanciación</h2>
            </div>


            <div class="main-box-body clearfix">
                 <?php
                echo $this->renderForm($this->formRefinanciacion, \ZfMetal\Commons\Consts::STYLE_VERTICAL, \ZfMetal\Commons\Consts::COLUMNS_FOUR,[]);
                ?>
            </div>
        </div>
    </div>

</div>