
<div class="row ">
    <div class="col-lg-6">
        <div class="main-box  clearfix">

            <div class="main-box-header clearfix">
                <h2>Actualización</h2>
            </div>


            <div class="main-box-body clearfix">

                <?php
                echo $this->renderForm($this->form, \ZfMetal\Commons\Consts::STYLE_VERTICAL, \ZfMetal\Commons\Consts::COLUMNS_TWO);
                ?>
            </div>

        </div>
    </div>

    <div class="col-lg-6">
        <div class="main-box  clearfix">

            <div class="main-box-header clearfix">
                <h2>Refinanciación</h2>
            </div>


            <div class="main-box-body clearfix">
            </div>
        </div>
    </div>

</div>