<div class="row">
    <div class="col-lg-10 col-md-10 col-sm-12 col-xs-12">
        <?php if ($this->cliente): ?>

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title"> <?php echo $this->translate('Cliente'); ?>: <strong><?php echo $this->cliente->getRazonSocial(); ?></strong></h4>
                </div>
                <div class="panel-body">

                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#clienteTab" data-toggle="tab" aria-expanded="true">Cliente</a>
                        </li>
                        <li class=""><a href="#productosTab" data-toggle="tab" aria-expanded="true">Productos</a>
                        </li>
                        <li class=""><a href="#bitacoraTab" data-toggle="tab" aria-expanded="false">Bitacora</a>
                        </li>

                    </ul>

                    <div class="tab-content">
                        <div class="tab-pane fade active in" id="clienteTab">
                            <div id="cliente-content">
                                <?php echo $this->partial("acef/manager-cliente/ver-cliente", ["cliente" => $this->cliente]); ?>
                            </div>

                        </div>
                        <div class="tab-pane fade" id="productosTab">

                            <h4>Productos</h4>
                            <br>
                            <div id="productos-content">
                                <i class="glyphicon glyphicon-transfer"> Cargando...</i>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="bitacoraTab">
                            <h4>Bitacora</h4>
                            <br>
                            <div id="bitacora-content">
                                <i class="glyphicon glyphicon-transfer"> Cargando...</i>
                            </div>
                        </div>

                    </div>

                </div>

            </div>

        <?php endif; ?>
    </div>
</div>

<?php
$this->headScript()
        ->appendScript($this->partial('acef/manager-cliente/js/cliente.js'), 'text/javascript');
?>