<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
<div class="clearfix" style="padding: 15px">
	<h2 style="font-size: 14px; padding-bottom: 10px;
color: #999;">Deuda Actual</h2> 
	<i class="fa fa-usd" style="font-size: 15px;
line-height: 1.5;
float: left;
margin-right: 5px;
margin-bottom: 10px;
font-weight: 600;"></i><span style="font-size: 2em;
line-height: 1;" id="parcialDeudas1"><?= $deuda ?></span>
</div>
</div>
<div style="padding-left: 25px; padding-right: 25px; margin-bottom: 10px;">
	<h2 style=" font-weight: normal; border-bottom: 1px solid #e5e5e5;">Pagos</h2> 
</div>

<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
<?php echo $this->Grid($this->grid);?>
</div>
<div class="clearfix"></div>
<script>
	$('#parcialDeudas2').text($('#parcialDeudas1').text());
</script>