<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
<div class="clearfix" style="padding: 15px">
	<h2 style="font-size: 14px;
color: #999;">Deuda Actual</h2> 
	<i class="fa fa-usd" style="font-size: 15px;
line-height: 1.5;
float: left;
padding: 5px
font-weight: 600;"></i><span style="font-size: 2em;
line-height: 1;"><?= $deuda ?></span>
</div>
</div>

<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
<?php echo $this->Grid($this->grid);?>
</div>
<div class="clearfix"></div>