<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
<div class="clearfix">
<div class="boxDeuda" style="padding: 15px">
	<h2 class="titleDeuda">Deuda Contable</h2> 
	<i class="fa fa-usd symbolMoney"></i><span style="font-size: 2em;
line-height: 1;" id="deudaContable1"><?= $deudaContable ?></span>
</div>
<div class="boxDeuda" style="padding: 15px">
	<h2 class="titleDeuda">Deuda Financiera</h2> 
	<i class="fa fa-usd symbolMoney"></i><span style="font-size: 2em;
line-height: 1;" id="deudaFinanciera1"><?= $deuda ?></span>
</div>
</div>
</div>
<div style="padding-left: 25px; padding-right: 25px; margin-bottom: 10px;">
	<h2 style=" font-weight: normal; border-bottom: 1px solid #e5e5e5;">Pagos</h2> 
</div>

<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
<?php echo $this->Grid($this->grid);?>
</div>
<div class="clearfix"></div>
<script>
	$('#deudaFinanciera2').text($('#deudaFinanciera1').text());
	$('#deudaContable2').text($('#deudaContable1').text());
</script>