<div class="col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-12">
    <table class="table table-striped table-right">
        <tr>
            <th class="text-right">Id:</th><td class="text-left" id="clienteId"><?php echo $this->cliente->getId(); ?></td>
        </tr>
        <tr>
            <th class="text-right">Razón Social:</th><td class="text-left"><?php echo $this->cliente->getRazonSocial(); ?></td>
        </tr>
        <tr>
            <th class="text-right">Cuit:</th><td class="text-left"><?php echo $this->cliente->getCuit(); ?></td>
        </tr>
        <tr>
            <th class="text-right">Domicilio:</th><td class="text-left"><?php echo $this->cliente->getDomicilio(); ?></td>
        </tr>
        <tr>
            <th class="text-right">Localidad:</th><td class="text-left"><?php echo $this->cliente->getLocalidad(); ?></td>
        </tr>
        <tr>
            <th class="text-right">Teléfono:</th><td class="text-left"><?php echo $this->cliente->getTelefono(); ?></td>
        </tr>
        <tr>
            <th class="text-right">Teléfono Alternativo:</th><td class="text-left"><?php echo $this->cliente->getTelefonoAlternativo(); ?></td>
        </tr>
        <tr>
            <th class="text-right">Email:</th><td class="text-left"><?php echo $this->cliente->getEmail(); ?></td>
        </tr>
        <tr>
            <th class="text-right">Fecha de Asignación:</th><td class="text-left"><?php echo $this->cliente->getFechaAsignacion(); ?></td>
        </tr>
        <tr>
            <th class="text-right">Fecha de Retención:</th><td class="text-left"><?php echo $this->cliente->getFechaRetencion(); ?></td>
        </tr>
        <tr>
            <th class="text-right">Fecha de Actualización:</th><td class="text-left"><?php echo $this->cliente->getFechaActualizacion(); ?></td>
        </tr>
        <tr>
            <th class="text-right">Responsable:</th><td class="text-left"><?php echo $this->cliente->getResponsable(); ?></td>
        </tr>
    </table>
    <button class="btn btn-warning pull-right" onclick="editarCliente(<?php echo $this->cliente->getId(); ?>)">Editar Cliente</button>
</div>
