<?php
$form = $this->form;
$form->prepare();
$elementsReady = array();
?>
<div class="row">
    <div class="main-box">
        <header class="main-box-header clearfix">
            <h2><?= $form->getName(); ?></h2>
        </header>
        <div class="main-box-body clearfix">
            <?php echo $this->form()->openTag($form); ?>

            <!--HORIZONTAL GROUPS-->
            <?php if (count($this->horizontalGroups)): ?>
                <?php foreach ($this->horizontalGroups as $groupName => $group): ?>
                    <div id="form-group-<?php echo $groupName; ?>">
                        <legend><?php echo $this->translate($groupName); ?></legend>
                        <?php foreach ($group as $item): ?>
                            <?php if ($form->has($item) && !in_array($item, $elementsReady)): ?>
                                <?php $element = $form->get($item); ?>
                                <?php $elementsReady[] = $item; ?>
                                <div class="<?php echo ($element->getAttribute('type') !== "hidden") ? $this->columnClass : "input-hidden"; ?>">
                                    <?php echo $this->renderFormElement($element, $this->style); ?>
                                </div>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </div>
                    <div class="clearfix"></div>
                <?php endforeach; ?>

            <?php endif; ?>

            <!--VERTICAL-GROUPS-->
            <?php if (count($this->verticalGroups)): ?>
                <?php foreach ($this->verticalGroups as $groupName => $group): ?>
                    <div class="<?php echo $this->columnClass; ?>">

                        <div id="form-group-<?php echo $groupName; ?>">
                            <legend><?php echo $this->translate($groupName); ?></legend>
                            <?php foreach ($group as $item): ?>
                                <?php if ($form->has($item) && !in_array($item, $elementsReady)): ?>
                                    <?php $element = $form->get($item); ?>
                                    <?php $elementsReady[] = $item; ?>
                                    <?php echo $this->renderFormElement($element, $this->style); ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </div>
                    </div>
                <?php endforeach; ?>

            <?php endif; ?>        


            <!--OTHERS-->
            <?php foreach ($form as $element) : ?>
                <?php if (!in_array($element->getName(), $elementsReady) && $element->getAttribute('type') !== "submit" && $element->getAttribute('type') !== "button"): ?>
                    <div class="<?php echo ($element->getAttribute('type') !== "hidden") ? $this->columnClass : "input-hidden"; ?>">
                        <?php echo $this->renderFormElement($element, $this->style); ?>
                    </div>

                <?php endif; ?>

            <?php endforeach; ?>


            <!--SUBMIT & BUTTONS-->
            <div class="col-lg-12 col-xs-12">
                <?php foreach ($form as $element) : ?>

                    <?php if ($element->getAttribute('type') === "submit" || $element->getAttribute('type') === "button"): ?>
                        <?php echo $this->renderFormElement($element, $this->style); ?>
                    <?php endif; ?>

                <?php endforeach; ?>

                <?php if (strpos($this->form->getAttribute('action'),'java') === false) : ?>
                    <div class="pull-right">
                        <a class="btn btn-default" href="<?php echo $this->url($this->route, array(), array('query' => $this->routeParams), true); ?>" >Cancel</a>
                    </div>
                <?php endif; ?>
            </div>

            <?php echo $this->form()->closeTag($form); ?>
        </div>       
    </div>
</div>

