<?php echo $this->Grid($this->grid); ?>

<script type="text/javascript">
	$(document).on('ready', function () {
		$('#fechaAsignacion').on('change', function(){
			fechaAsignacion = $('#fechaAsignacion').val();
			if(validarFecha(fechaAsignacion)){
				$('#fechaRetencion').val(getFechaRetencion(fechaAsignacion));
			}			
		});

		function validarFecha(fecha){
			 //Funcion validarFecha 
			 //Escrita por Buzu feb 18 2010. (FELIZ CUMPLE BUZU!!!
			 //valida fecha en formato aaaa-mm-dd
			 var fechaArr = fecha.split('-');
			 var aho = fechaArr[0];
			 var mes = fechaArr[1];
			 var dia = fechaArr[2];
			 
			 var plantilla = new Date(aho, mes - 1, dia);//mes empieza de cero Enero = 0

			 if(!plantilla || plantilla.getFullYear() == aho && plantilla.getMonth() == mes -1 && plantilla.getDate() == dia){
			 return true;
			 }else{
			 return false;
			 }
		}

		function getFechaRetencion(fechaAsignacion) {
			date = new Date(fechaAsignacion);
			date.setDate(date.getDate() + 90)
			var curr_date = date.getDate();
    		var curr_month = date.getMonth() + 1; //Months are zero based
    		var curr_year = date.getFullYear();
    		if(curr_date < 10){
    			curr_date = '0'+ curr_date;
    		}
    		if(curr_month < 10){
    			curr_month = '0'+ curr_month;
    		}
    		return curr_year + "-" + curr_month + "-" +  curr_date;
		}
});


</script>