<?php
echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/assets/favicon.ico'))
        ->appendStylesheet($this->basePath() . '/shared/centaurus/global/bootstrap.css')
        ->appendStylesheet($this->basePath() . '/shared/centaurus/libraries/font-awesome.css')
        ->appendStylesheet($this->basePath() . '/shared/centaurus/libraries/nanoscroller.css')
        ->appendStylesheet($this->basePath() . '/shared/centaurus/global/theme_styles.css')
;
?> 
