<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

        <title>Centaurus - Bootstrap Admin Template</title>

        <!-- Le styles -->
        <?= $this->partial('layout/css'); ?>
        <?= $this->partial('layout/js'); ?>


    </head>
    <body class="fixed-header pace-done">
        <div id="theme-wrapper">
            <header class="navbar" id="header-navbar">
                <div class="container">
                    <a href="#" id="logo" class="navbar-brand">
                        <img src="<?= $this->basePath() ?>/img/centaurus/logo.png" alt="" class="normal-logo logo-white"/>
                        <img src="<?= $this->basePath() ?>/img/centaurus/logo-black.png" alt="" class="normal-logo logo-black"/>
                        <img src="<?= $this->basePath() ?>/img/centaurus/logo-small.png" alt="" class="small-logo hidden-xs hidden-sm hidden"/>
                    </a>
                    <div class="clearfix">
                        <button class="navbar-toggle" data-target=".navbar-ex1-collapse" data-toggle="collapse" type="button">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="fa fa-bars"></span>
                        </button>

                        <div class="nav-no-collapse navbar-left pull-left hidden-sm hidden-xs">
                            <ul class="nav navbar-nav pull-left">
                                <li>
                                    <a class="btn" id="make-small-nav">
                                        <i class="fa fa-bars"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>


                        <div class="nav-no-collapse pull-right" id="header-nav">

                            <ul class="nav navbar-nav pull-right">
<!--                                <li class="mobile-search">
                                    <a class="btn">
                                        <i class="fa fa-search"></i>
                                    </a>

                                    <div class="drowdown-search">
                                        <form role="search">
                                            <div class="form-group">
                                                <input type="text" class="form-control" placeholder="Search...">
                                                <i class="fa fa-search nav-search-icon"></i>
                                            </div>
                                        </form>
                                    </div>

                                </li>-->

                                <li class="dropdown profile-dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                        <img src="<?= $this->basePath() ?>/img/centaurus/samples/scarlet-159.png" alt=""/>
                                        <span class="hidden-xs">Scarlett Johansson</span> <b class="caret"></b>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li><a href="user-profile.html"><i class="fa fa-user"></i>Profile</a></li>
                                        <li><a href="#"><i class="fa fa-cog"></i>Settings</a></li>
                                        <li><a href="#"><i class="fa fa-envelope-o"></i>Messages</a></li>
                                        <li><a href="#"><i class="fa fa-power-off"></i>Logout</a></li>
                                    </ul>
                                </li>
                                <li class="hidden-xxs">
                                    <a class="btn">
                                        <i class="fa fa-power-off"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </header>
            <div id="page-wrapper" class="container nav-small">
                <div class="row">
                    <div id="nav-col">
                        <section id="col-left" class="col-left-nano">
                            <div id="col-left-inner" class="col-left-nano-content">
                                <div id="user-left-box" class="clearfix hidden-sm hidden-xs">
                                    <img alt="" src="<?= $this->basePath() ?>/img/centaurus/samples/scarlet-159.png" />
                                    <div class="user-box">
                                        <span class="name">
                                            Welcome<br/>
                                            Scarlett
                                        </span>
                                        <span class="status">
                                            <i class="fa fa-circle"></i> Online
                                        </span>
                                    </div>
                                </div>
                                <div class="collapse navbar-collapse navbar-ex1-collapse" id="sidebar-nav">	
                                    <ul class="nav nav-pills nav-stacked">
                                        <li class="active">
                                            <a href="#">
                                                <i class="fa fa-dashboard"></i>
                                                <span>Dashboard</span>
                                                <span class="label label-info label-circle pull-right">28</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#" class="dropdown-toggle">
                                                <i class="fa fa-table"></i>
                                                <span>Tables</span>
                                                <i class="fa fa-chevron-circle-right drop-icon"></i>
                                            </a>
                                            <ul class="submenu">
                                                <li>
                                                    <a href="tables.html">
                                                        Simple
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="tables-advanced.html">
                                                        Advanced
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="users.html">
                                                        Users
                                                    </a>
                                                </li>
                                            </ul>
                                        </li>
                                        <li>
                                            <a href="#" class="dropdown-toggle">
                                                <i class="fa fa-envelope"></i>
                                                <span>Email</span>
                                                <i class="fa fa-chevron-circle-right drop-icon"></i>
                                            </a>
                                            <ul class="submenu">
                                                <li>
                                                    <a href="email-inbox.html">
                                                        Inbox
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="email-detail.html">
                                                        Detail
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="email-compose.html">
                                                        Compose
                                                    </a>
                                                </li>
                                            </ul>
                                        </li>
                                        <li>
                                            <a href="#" class="dropdown-toggle">
                                                <i class="fa fa-bar-chart-o"></i>
                                                <span>Graphs</span>
                                                <i class="fa fa-chevron-circle-right drop-icon"></i>
                                            </a>
                                            <ul class="submenu">
                                                <li>
                                                    <a href="graphs-morris.html">
                                                        Morris &amp; Mixed
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="graphs-flot.html">
                                                        Flot
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="graphs-dygraphs.html">
                                                        Dygraphs
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="graphs-xcharts.html">
                                                        xCharts
                                                    </a>
                                                </li>
                                            </ul>
                                        </li>
                                        <li>
                                            <a href="widgets.html">
                                                <i class="fa fa-th-large"></i>
                                                <span>Widgets</span>
                                                <span class="label label-success pull-right">New</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#" class="dropdown-toggle">
                                                <i class="fa fa-desktop"></i>
                                                <span>Pages</span>
                                                <i class="fa fa-chevron-circle-right drop-icon"></i>
                                            </a>
                                            <ul class="submenu">
                                                <li>
                                                    <a href="calendar.html">
                                                        Calendar
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="gallery.html">
                                                        Gallery
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="gallery-v2.html">
                                                        Gallery v2
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="pricing.html">
                                                        Pricing
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="projects.html">
                                                        Projects
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="team-members.html">
                                                        Team Members
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="timeline.html">
                                                        Timeline
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="timeline-grid.html">
                                                        Timeline Grid
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="user-profile.html">
                                                        User Profile
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="search.html">
                                                        Search Results
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="invoice.html">
                                                        Invoice
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="intro.html">
                                                        Tour Layout
                                                    </a>
                                                </li>
                                            </ul>
                                        </li>
                                        <li>
                                            <a href="#" class="dropdown-toggle">
                                                <i class="fa fa-edit"></i>
                                                <span>Forms</span>
                                                <i class="fa fa-chevron-circle-right drop-icon"></i>
                                            </a>
                                            <ul class="submenu">
                                                <li>
                                                    <a href="form-elements.html">
                                                        Elements
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="x-editable.html">
                                                        X-Editable
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="form-wizard.html">
                                                        Wizard
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="form-wizard-popup.html">
                                                        Wizard popup
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="form-wysiwyg.html">
                                                        WYSIWYG
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="form-summernote.html">
                                                        WYSIWYG Summernote
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="form-ckeditor.html">
                                                        WYSIWYG CKEditor
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="form-dropzone.html">
                                                        Multiple File Upload
                                                    </a>
                                                </li>
                                            </ul>
                                        </li>
                                        <li>
                                            <a href="#" class="dropdown-toggle">
                                                <i class="fa fa-desktop"></i>
                                                <span>UI Kit</span>
                                                <i class="fa fa-chevron-circle-right drop-icon"></i>
                                            </a>
                                            <ul class="submenu">
                                                <li>
                                                    <a href="ui-elements.html">
                                                        Elements
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="notifications.html">
                                                        Notifications &amp; Alerts
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="modals.html">
                                                        Modals
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="video.html">
                                                        Video
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="#" class="dropdown-toggle">
                                                        Icons
                                                        <i class="fa fa-chevron-circle-right drop-icon"></i>
                                                    </a>
                                                    <ul class="submenu">
                                                        <li>
                                                            <a href="icons-awesome.html">
                                                                Awesome Icons
                                                            </a>
                                                        </li>
                                                        <li>
                                                            <a href="icons-halflings.html">
                                                                Halflings Icons
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </li>
                                                <li>
                                                    <a href="ui-nestable.html">
                                                        Nestable List
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="typography.html">
                                                        Typography
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="#" class="dropdown-toggle">
                                                        3 Level Menu
                                                        <i class="fa fa-chevron-circle-right drop-icon"></i>
                                                    </a>
                                                    <ul class="submenu">
                                                        <li>
                                                            <a href="#">
                                                                3rd Level
                                                            </a>
                                                        </li>
                                                        <li>
                                                            <a href="#">
                                                                3rd Level
                                                            </a>
                                                        </li>
                                                        <li>
                                                            <a href="#">
                                                                3rd Level
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </li>
                                            </ul>
                                        </li>
                                        <li>
                                            <a href="maps.html">
                                                <i class="fa fa-map-marker"></i>
                                                <span>Google Maps</span>
                                                <span class="label label-danger pull-right">Updated</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#" class="dropdown-toggle">
                                                <i class="fa fa-file-text-o"></i>
                                                <span>Extra pages</span>
                                                <i class="fa fa-chevron-circle-right drop-icon"></i>
                                            </a>
                                            <ul class="submenu">
                                                <li>
                                                    <a href="faq.html">
                                                        FAQ
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="emails.html">
                                                        Email Templates
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="login.html">
                                                        Login
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="login-full.html">
                                                        Login Full
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="registration.html">
                                                        Registration
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="registration-full.html">
                                                        Registration Full
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="forgot-password.html">
                                                        Forgot Password
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="forgot-password-full.html">
                                                        Forgot Password Full
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="lock-screen.html">
                                                        Lock Screen
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="lock-screen-full.html">
                                                        Lock Screen Full
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="error-404.html">
                                                        Error 404
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="error-404-v2.html">
                                                        Error 404 Nested
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="error-500.html">
                                                        Error 500
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="extra-grid.html">
                                                        Grid
                                                    </a>
                                                </li>
                                            </ul>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </section>
                    </div>
                    <div id="content-wrapper">

                        <?= $this->content; ?>

                        <?= $this->partial('layout/footer'); ?>

                    </div>
                </div>
            </div>
        </div>


    </body>
</html>