<div id="nav-col">
    <section id="col-left" class="col-left-nano">
        <div id="col-left-inner" class="col-left-nano-content">
            <div id="user-left-box" class="clearfix hidden-sm hidden-xs">
                <img alt="" src="<?= $this->basePath() ?>/img/centaurus/samples/scarlet-159.png" />
                <div class="user-box">
                    <span class="name">
                        Welcome<br/>
                        Scarlett
                    </span>
                    <span class="status">
                        <i class="fa fa-circle"></i> Online
                    </span>
                </div>
            </div>
            <div class="collapse navbar-collapse navbar-ex1-collapse" id="sidebar-nav">	
                
                <?= $this->renderMenu(\ZfMetal\Commons\Consts::STYLE_MENU_VERTICAL, 'default', 'nav nav-pills nav-stacked'); ?>
                
            </div>
        </div>
    </section>
</div>