<?php
$this->flashCurrent();
?>
<style>
    .blue-bg {
        background-color: #2C3E50 !important;
    }
</style>
<div class="row">
    <div class="col-xs-12 col-md-12">

        <div class="row" id="user-profile">
            <div class="col-lg-3 col-md-4 col-sm-4">
                <div class="main-box clearfix">
                    <header class="main-box-header clearfix">
                        <h2><?= ucfirst($user->getName()); ?></h2>
                    </header>

                    <div class="main-box-body clearfix">
                        <div class="profile-status">
                            <i class="fa fa-circle"></i> Online
                        </div>

                        <img src="<?= $this->basePath($this->getSecurityOptions()->getProfilePicturePathRelative()) . $user->getImg(); ?>" alt="" class="profile-img img-responsive center-block" />



                        <?php echo $this->form()->openTag($formImg) ?>

                        <div class="btn-block">
                            <?php echo $this->formElement($formImg->get('img')); ?>

                        </div>
                        <div class="btn-block">
                            <?php echo $this->formElement($formImg->get('submitbtn')); ?>
                        </div>


                        <?php echo $this->form()->closeTag($formImg); ?>

                        <?php if($user->getCreateAt()):?>
                        <hr>                      
                        <div class="profile-since">
                            <?= $this->translate('Miembro desde')?>: <?=$user->getCreateAt()->format('d m Y');?>
                        </div>
                        <?php endif; ?>
                        <!--                        <div class="profile-details">
                                                    <ul class="fa-ul">
                                                        <li><i class="fa-li fa fa-truck"></i>Orders: <span>456</span></li>
                                                        <li><i class="fa-li fa fa-comment"></i>Posts: <span>828</span></li>
                                                        <li><i class="fa-li fa fa-tasks"></i>Tasks done: <span>1024</span></li>
                                                    </ul>
                                                </div>-->
                        <hr>
                        <div class="profile-message-btn center-block text-center">
                            <a class="btn btn-default btn-block" href="<?= $this->url('zf-metal.user/profile/password-update'); ?>" >
                                <span class="fa fa-lock"></span>
                                <?php echo $this->translate('Modificar Password'); ?>
                            </a>
                        </div>
                    </div>

                </div>
            </div>

            <div class="col-lg-9 col-md-8 col-sm-8">
                <div class="main-box clearfix">
                    <div class="main-box clearfix profile-box-menu">
                        <div class="main-box-body clearfix">
                            <div class="profile-box-header blue-bg clearfix">
                                <h2><?= ucfirst($user->getName()); ?></h2>
                            </div>
                            <div class="profile-box-content clearfix">
                                <ul class="menu-items">
                                    <li>
                                        <a href="#" class="clearfix">
                                            <i class="fa fa-envelope fa-lg"></i> Email:
                                            <span class=""><?= $user->getEmail(); ?></span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#" class="clearfix">
                                            <i class="fa fa-cubes fa-lg"></i> Roles: 

                                            <?php foreach ($user->getRoles() as $rol) : ?>
                                                <span class="label label-info tags"><?= $rol->getName(); ?></span>
                                            <?php endforeach; ?>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#" class="clearfix">
                                            <i class="fa fa-calendar fa-lg"></i> Permissions:
                                            <?php foreach ($user->getRoles() as $rol) : ?>
                                                <?php foreach ($rol->getPermissions() as $permission) : ?>

                                                    <span class="label label-success tags"><?= $rol->getName() . ' - ' . $permission->getName(); ?></span>

                                                <?php endforeach; ?>
                                            <?php endforeach; ?>
                                        </a>
                                    </li>

                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>
</div>

