<a href="<?= $this->url('Acef/Estados/Grid'); ?>">
    <div class="col-md-4 col-sm-6 col-xs-12">
        <div class="main-box small-graph-box red-bg">
            <span class="headline">Tipos de Estado</span>
            <span class="subinfo">
                <i class="fa fa-caret-square-o-right"></i> Administrar
            </span>
        </div>
    </div>
</a>
<a href="<?= $this->url('Acef/TipoProducto/Grid'); ?>">
    <div class="col-md-4 col-sm-6 col-xs-12">
        <div class="main-box small-graph-box green-bg">
            <span class="headline">Tipos de Producto</span>
            <span class="subinfo">
                <i class="fa fa-caret-square-o-right"></i> Administrar
            </span>
        </div>
    </div>
</a>